### ISSUE TITLE
Return 200 instead of 204 for multiple endpoints

### ISSUE THREAD

**Issue by marfavi** [AnalogIO/analog-core#148]
Our app & generated http client does not take the return type of 204 responses (No Content; returns Null) into account properly.

On Sun 23 Apr, we decided that the easiest solution to this problem is to remove the possibility of returning 204 with no content, and instead opt into returning 200 with e.g. an empty array if an array of values is the expected return type.

One example is the GET V2 Purchases endpoint. It should return 200 and an empty array instead of 204 and Null / (no bytes).

This change should not warrant a version bump to endpoints, as we don't rely on the 204 return type in any clients anyway.

**Comment by jonasanker** [comment]
@marfavi This has been solved in https://github.com/AnalogIO/analog-core/commit/cb1ae4878b10937408213faee4ba7efe1d54b6be
