### ISSUE TITLE
Fix null purchase statuses in database and make the status field non-nullable

### ISSUE THREAD

**Issue by marfavi** [AnalogIO/analog-core#187]
We have encountered an issue with null purchase statuses in the coffeecard app. Some purchases, particularly older ones, are incorrectly displayed as failed due to their purchase status being null. The root of this problem lies in the handling of null values in the `Status` field of our `Purchase` entity.

Here's the `Status` field in the `Purchase` entity:

```cs
// Status is nullable for migration purposes
/// <summary>
/// Purchase Status. The status should also reflect the status at the external payment provider
/// </summary>
/// <value>Status</value>
/// <example>Completed</example>
public PurchaseStatus? Status { get; set; }
```

This field was initially designed to be nullable for migration purposes, as older purchases in the database did not have a purchase status. However, it has led to inconsistent handling of these null statuses, which results in purchases being misidentified in the application.

It is our proposal to change this field to required (non-nullable), and to update the existing `Purchase` entity entries in the database to have a valid purchase status. By doing this, we ensure that:

1. All purchases will have a valid status, eliminating any ambiguity caused by null values.
2. The application will have a reliable source of purchase status to use, enhancing the user experience.

The steps for implementation are:

1. Update the `Status` field in the `Purchase` entity to be non-nullable.
2. Correct the statuses of the purchases currently set as null in the database. Determine their correct statuses wherever possible.
3. Implement a migration to enforce this new non-nullable requirement in the database.

Addressing this issue will ensure the integrity of our purchase history.

**Comment by jonasanker** [comment]
I know this is a minor and you might be aware but the order must be that data is migrated before the non-nullable constraint is enforced else enforcing the constraint will fail :)

**Comment by jonasanker** [comment]
Once all purchase statuses have been updated, we can also drop the completed boolean column as the purchase status will take over from this.

**Comment by jonasanker** [comment]
I would like to suggest that Purchases with `Completed` == `0` are set to PurchaseStatus `Cancelled`, and those with `Completed` == `1` are set to `Completed`.
