### ISSUE TITLE
New MobilePay Payments API

### ISSUE THREAD

**Issue by jonasanker** [AnalogIO/analog-core#31]
Track sub issues related to implementing support for new MobilePay Payments API
Investigate the work needed in the backend to migrate to the new Mobile Payments API. Documentation is found here https://mobilepaydev.github.io/MobilePay-Payments-API/docs/introduction

# Sub issues

Link to flutter app issue https://github.com/AnalogIO/coffeecard_app/issues/43

**Comment by marfavi** [comment]
Finished
