### ISSUE TITLE
Generate Voucher codes API

### ISSUE THREAD

**Issue by jonasanker** [AnalogIO/analog-core#34]
A new REST endpoint for generating a list of voucher codes

**Preliminary Requirements**
- Endpoint needs either an admin token authorization or requires a user to be in a particular user group

_Input_
- Voucher prefix
- ProductId
- Number of voucher codes to generate
- Description of voucher code creation
- Requester

_Output_
List of vouchers code with
- Voucher Code
- ProductId
- ProductName
- Issue date and time

_Considerations_
- Create a new controller for voucher codes. Copy existing `redeemvoucher` endpoint to the new controller and keep the old one for backwards compatibility.
- Expand Voucher code data model with a description data field and new requester/creator data field which will store the user information about the voucher code purpose and the user who created the voucher code.

_Voucher code format_
- Vouchers are generated with the format `ABC-XXXXXXXX` where `ABC` is a user-defined prefix and `XXXXXXXX` is a 8 characters random alphanumeric string. Everything capitalized.

_Notes_
- A simple integration test should be created for testing the generation of app codes.
- Code documentation with `<summary>`, `<value>` and `<example>` should be added as a minimum on model classes and endpoints methods.
- Apply a uniqueness constraint on the  `Code` column

**Comment by jonasanker** [comment]
@fremartini I have updated the GitHub issue with new two new data fields; requester and description. 

In the first version where we will use a an adminToken for authorisation, the userId should be part of the endpoint request. However in a future version, we will take it from the user claim.

**Comment by jonasanker** [comment]
@fremartini Can you part of this ticket put a uniqueness constraint on the `Code` column in the `Vouchers` table?

**Comment by fremartini** [comment]
@jonasanker i'll have a look

**Comment by fremartini** [comment]
@jonasanker has this been solved?

**Comment by jonasanker** [comment]
Nope. It's not urgent but feel free to continue if you want to
