### ISSUE TITLE
Include User Type in user responses 

### ISSUE THREAD

**Issue by jonasanker** [AnalogIO/analog-core#92]
The user type, e.g. barista should be returned from the account endpoints.

**Comment by fremartini** [comment]
I assume this task requires extending the 'UserDTO' returned from the Get endpoint in AccountController with the 'UserGroup' column from the 'Users' table, correct? Then the type can be mapped in the Flutter app?

**Comment by TTA777** [comment]
An alternative approach to implementing this would be implementing user roles as part of the jwt token that we use to authenticate with. The app would then be able to read the token to show any usergroup the user belongs to

**Comment by jonasanker** [comment]
@TTA777 , @fremartini  I belive the requested functionality has already been developed, right?

**Comment by TTA777** [comment]
Yes, this is already implemented
